[ALP-85] PUT /volunteers working
CodetheChangeFoundation/alp pull request #100
Opened 2020-03-28 18:54 UTC by michaelfromyeg

Updated getVolunteers and getVolunteerNames to check for isDeleted, added query on button press, table refreshes after button press.

2020-04-02 04:25 UTC, justinkkwan requested changes

2020-04-02 04:25 UTC, justinkkwan commented on aunt-leahs-app/src/components/CustomTable.jsx
> +    .replace(/([A-Z])/g, " $1")
What does this do?

2020-04-02 04:25 UTC, justinkkwan commented on aunt-leahs-app/src/components/CustomTable.jsx
> +    .replace(/^./, str => str.toUpperCase());
This entire line can be replaced with `.toUpperCase()`, I think

2020-04-02 04:25 UTC, justinkkwan commented on aunt-leahs-app/src/components/CustomTable.jsx
> +                        : row[key]}
The logic should be put into a function, imo

2020-04-02 04:25 UTC, justinkkwan commented on aunt-leahs-functions/shifts/index.js
> +    var queryString = "UPDATE Shift SET isDeleted = 1;";
Needs `WHERE` condition

2020-04-02 04:25 UTC, justinkkwan commented on aunt-leahs-functions/volunteers/index.js
> +        body: JSON.stringify(volunteers)
I don't think this needs to be stringify'd

2020-04-02 04:25 UTC, justinkkwan commented on aunt-leahs-functions/volunteers/index.js
> +          body: "Error occurred deleting volunteers from the database " + err
Maybe end the string with `: \n` before the `+  err`?

2020-04-03 06:52 UTC, thaingocnguyen requested changes
There is still a warning when the volunteer data page is loaded due to missing keys. Can you look modify volunteer data is set to fix this?

Other than this, clear functionality is working

2020-04-03 18:37 UTC, michaelfromyeg commented on aunt-leahs-app/src/components/CustomTable.jsx
> +    .replace(/([A-Z])/g, " $1")
[Looks](https://stackoverflow.com/questions/2418497/javascript-regexp-pattern-matching) like it adds spacing to camelCase

2020-04-03 18:41 UTC, michaelfromyeg commented on aunt-leahs-app/src/components/CustomTable.jsx
> +    .replace(/^./, str => str.toUpperCase());
I think this just grabs the first character (^) and capitalizes it, so it fixes the lowerCaseCase in combination with the last one to "Lower Camel Case".

2020-04-03 18:46 UTC, michaelfromyeg commented on aunt-leahs-app/src/components/CustomTable.jsx
> +                        : row[key]}
Agreed, done!

2020-04-04 02:38 UTC, codygagnon commented
Michael, can you please resolve the conflicts?

2020-04-04 03:09 UTC, justinkkwan approved these changes
👍

2020-04-04 03:14 UTC, codygagnon approved these changes

2020-04-04 03:27 UTC, thaingocnguyen approved these changes

2020-04-04 03:28 UTC, merged