ALP-92: /history endpoint for fetching and updating last cleared time and last exported time
CodetheChangeFoundation/alp pull request #93
Opened 2020-03-19 05:54 UTC by thaingocnguyen

2020-03-28 20:54 UTC, michaelfromyeg requested changes
Very minor comments, overall looks really good.

2020-03-28 20:54 UTC, michaelfromyeg commented on aunt-leahs-app/src/pages/AdminShiftDataPage.jsx
> +				isExportAction: 0,
This should be 1, right?

2020-03-28 20:54 UTC, michaelfromyeg commented on aunt-leahs-functions/history/index.js
> +                    context.done();
context.done(err)

2020-03-28 20:54 UTC, michaelfromyeg commented on aunt-leahs-functions/history/index.js
> +                    context.done();
context.done(err)

2020-04-01 04:59 UTC, michaelfromyeg approved these changes

2020-04-01 15:14 UTC, codygagnon commented
Thai, can you please resolve the conflicts on this PR so that it can be approved and merged?

2020-04-04 02:37 UTC, codygagnon approved these changes

2020-04-04 02:39 UTC, merged